name: Release WordPress Plugin
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create ZIP
        run: |
          zip -r oembed-widget-for-telegram-posts.zip .
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: oembed-widget-for-telegram-posts.zip
          name: Release ${{ github.ref_name }}
          body: "Release notes for ${{ github.ref_name }}"
